### ISSUE TITLE
Fix needed: README.md

### ISSUE THREAD

**Issue by Spirizeon** [ReDxDaGer/JUNKie#3]
**PROBLEMS**
1. File has formatting errors over [here](https://github.com/ReDxDaGer/JUNKie#getting-started)
2. In [here](https://github.com/ReDxDaGer/JUNKie#getting-started) bullets skip from 3. to 7. 
3. [This](https://github.com/ReDxDaGer/JUNKie#acknowledgements) section is no longer needed. 

**SOLUTION**
1. Make sure the syntax is inside the triple-quotes ( ` ) 
2. Order bullets from 1 to 4
3. Delete or replace the section

**Comment by ReDxDaGer** [comment]
Done!!
